config/routes.rb
Rails.application.routes.draw do
  root 'products#index'
  resources :products, only: [:index, :create] do
    get :link, on: :member
  end

  get 'vote/:id' => 'products#vote', as: :vote_product

  get 'auth/:provider/callback', to: 'auth_callbacks#create'
  get 'auth/failure', to: 'auth_callbacks#failure'
  delete 'sign_out', to: 'sessions#destroy', as: :sign_out
end

app/models/null_user.rb
class NullUser
  def name
    ""
  end

  def avatar
    "no-avatar.png"
  end
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :user

  acts_as_votable

  validates :name, :tagline, :url, presence: true
  validates :url, uniqueness: true

  def user
    super || NullUser.new
  end

  def to_date
    created_at.to_date
  end

  def vote_count
    votes_for.size
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :products

  acts_as_voter

  validates :uid, :username, uniqueness: true
  validates :uid, :username, :name, presence: true

  def to_param
    username
  end

  def first_name
    name.split(" ").first
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user
  def current_user
    @current_user ||= session[:user_id] && User.find(session[:user_id])
  end

  private

  helper_method :signed_in?
  def signed_in?
    !current_user.nil?
  end

  def authorize
    unless signed_in?
      session[:return_to] = request.original_url
      redirect_to '/auth/twitter', alert: 'You must login to access this page.'
    end
  end
end

app/controllers/auth_callbacks_controller.rb
class AuthCallbacksController < ApplicationController
  def create
    session[:return_to] = params[:return_to]
    @user = AuthMicroService.new(auth_hash).find_or_create

    session[:user_id] = @user.id
    redirect_to auth_origin, notice: "Welcome #{@user.name}!"
  end

  def failure
    redirect_to root_url, alert: "Something went wrong: #{params[:message].humanize}"
  end

  private

  def auth_hash
    request.env['omniauth.auth']
  end

  def auth_origin
    session[:return_to] || request.env['omniauth.origin'] || root_url
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :get_product, only: [:vote, :link]

  def index
    @product = current_user.products.new if signed_in?
    @products = Product.order(created_at: :desc).group_by(&:to_date)
  end

  def create
    @product = current_user.products.new(product_params)

    respond_to do |format|
      if @product.save
        @product.liked_by current_user
        format.js { @product }
      else
        format.html { redirect_to :back }
      end
    end
  end

  def vote
    unless current_user.voted_for? @product
      @product.liked_by current_user
    else
      @product.unliked_by current_user
    end

    respond_to do |format|
      format.js
    end
  end

  def link
    redirect_to @product.url
  end

  private

  def product_params
    params.require(:product).permit(:name, :tagline, :url)
  end

  def get_product
    @product = Product.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def destroy
    session[:user_id] = nil
    redirect_to root_url, notice: 'You have successfully signed out.'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_header.html.haml
%header
  .wrapper
    %h1.logo
      = link_to 'ProductShare', root_path
    %div.dropdown
      - if signed_in?
        = link_to '#', class: 'dropdown-link account-link' do
          = image_tag current_user.avatar, alt: current_user.name, class: 'account-avatar'
          = content_tag :span, current_user.name, class: 'account-username'
        %ul.dropdown-menu
          %li
            = link_to 'Sign out', sign_out_path, method: :delete, class: 'signout-link'
      - else
        = link_to 'Sign in with Twitter', '/auth/twitter', class: 'dropdown-link signin-link'
    = link_to '', '#', class: 'add-product-link'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ProductShare
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
    %link{:href => "http://fonts.googleapis.com/css?family=Open+Sans:400,600", :rel => "stylesheet", :type => "text/css"}/
  %body
    = render 'layouts/header'
    %main.wrapper
      = yield
    %footer.wrapper

app/views/products/_form.html.haml
= f.input :name, label: false, placeholder: 'Name'
= f.input :tagline, label: false, placeholder: 'Tagline'
= f.input :url, label: false, placeholder: 'URL'
= f.submit 'Share', label: false

app/views/products/_product.html.haml
= content_tag :li, class: 'post' do
  = link_to vote_product_path(product), class: "post-vote#{signed_in? && current_user.voted_for?(product) ? ' voted' : ''}", remote: true, data: { id: product.id } do
    %span.up ▲
    = content_tag :span, product.vote_count, class: 'post-vote-count', data: { id: product.id }
  %div.tooltip.post-avatar
    = image_tag product.user.avatar, title: product.user.name, class: 'tooltip-link'
    %div.tooltip-content
      = image_tag product.user.avatar
      = content_tag :span, product.user.name

  = link_to product.name, link_product_path(product), class: 'post-title', title: product.tagline
  = content_tag :span, product.tagline, class: 'post-tagline'

app/views/products/create.js.haml
:plain
  $("ul.post-list").first().append("#{escape_javascript(render(partial: @product))}");
  $("li.post a.post-vote[data-id=#{@product.id}]").addClass('voted');
  $("form#new_product").trigger("reset");

app/views/products/index.html.haml
- if signed_in?
  = simple_form_for @product, remote: true do |f|
    %h1 Post a new Product
    %h2 Share your product with the world
    = render 'form', f: f
- @products.each do |date, products|
  .date
    %h2= date.strftime("%A")
    %span= date.strftime("%B #{date.day.ordinalize}")
  %ul.post-list
    = render products.sort_by(&:vote_count).reverse

app/views/products/vote.js.haml
:plain
  $(".post-vote-count[data-id=#{@product.id}]").html('#{@product.vote_count}');
- if current_user.voted_for?(@product)
  :plain
    $("li.post a.post-vote[data-id=#{@product.id}]").addClass('voted');
- else
  :plain
    $("li.post a.post-vote[data-id=#{@product.id}]").removeClass('voted');